### ISSUE TITLE
aaaa

### ISSUE THREAD

**Issue by ghost** [KingFelix/emerald#15]
..........

**Comment by WaKeMaTTa** [comment]
Did you create any post?

**Comment by ghost** [comment]
............

**Comment by KingFelix** [comment]
Check the file name. Each post must have a name containing the date, for example: 2016-05-11-postname.md

**Comment by ghost** [comment]
..............

**Comment by WaKeMaTTa** [comment]
Try to execute this command: `jekyll build` in the terminal.

**Comment by KingFelix** [comment]
You entered the Front Matter on top of the posts?

**Comment by ghost** [comment]
..............

**Comment by WaKeMaTTa** [comment]
try this:

``` markdown
---
title: Testing 123
---
some text
```

**Comment by ghost** [comment]
..........

**Comment by ghost** [comment]
.............

**Comment by ppmanforthewin** [comment]
Are you hosting it on Github Pages or locally?

**Comment by ghost** [comment]
...........

**Comment by WaKeMaTTa** [comment]
Your code is a public repo?

**Comment by ghost** [comment]
................

**Comment by KingFelix** [comment]
Ok, I think the problem is the jekyll-paginate plugin. The latest Jekyll version doesn't support natively the pagination. You must add the plugin. 
Install the plugin:

`$ gem install jekyll-paginate`

Then in your _config.yml file add: 

`# Plugins`
`gems:`
  `- jekyll-paginate`

**Comment by ghost** [comment]
..............
