### ISSUE TITLE
Markdown theme

### ISSUE THREAD

**Issue by ximendatie** [KingFelix/emerald#18]
Hi, I'm a new learner.  I want to change emerabld's markdown theme, but have not found any ways.

Is there any way? I want to make emerabld's markdown theme be just the same as github's. For example the reference in github by '>', you can see 

> I'm a reference in github

but the same content , you will see different apperence:

![image](https://cloud.githubusercontent.com/assets/8457027/19638564/2575bb52-9a07-11e6-8504-faa98117862d.png)

So, the content become italic. And I want the former style.

Thanks

**Comment by KingFelix** [comment]
Hi, markdown output in simple HTML. Into the custom.scss file you can change the style for H1, H2, H3, blockquote, lists and so on. 
For example the '>' character in markdown output in blockquote tag.

**Comment by ximendatie** [comment]
many thanks 😊

**Comment by KingFelix** [comment]
You are welcome!
