### ISSUE TITLE
Enable "Template repository"

### ISSUE THREAD

**Issue by WaKeMaTTa** [KingFelix/emerald#39]
@KingFelix you should enable this option 

![Screenshot from 2019-08-12 13-09-35](https://user-images.githubusercontent.com/3450257/62861048-77436300-bd02-11e9-94c6-e779438036b7.png)

In the settings of this repository, to prevent this kind of pull requests:
- https://github.com/KingFelix/emerald/pull/38

**Comment by KingFelix** [comment]
Cool. Thanks.
