### ISSUE TITLE
[question] List style in post list ?

### ISSUE THREAD

**Issue by WaKeMaTTa** [KingFelix/emerald#5]
Hey @KingFelix 

First i need to say awesome theme :+1: 

I have a question: Why do you use list style in the post list [here](https://github.com/KingFelix/emerald/blob/master/index.html#L5) :question:

_PS: i forgot the label question._

**Comment by KingFelix** [comment]
Hi, @WaKeMaTTa!

Thanks for the compliment!  I'm very happy you appreciate my theme.
I use the list style just because the loop generate a list of post. 
It is not mandatory and you can still use div, section or whatever you prefer.

**Comment by WaKeMaTTa** [comment]
@KingFelix Ah! okey thnks
