### ISSUE TITLE
Support to author information

### ISSUE THREAD

**Issue by julianofischer** [KingFelix/emerald#6]
Hi, it would be amazing to have support for authors information.

**Comment by WaKeMaTTa** [comment]
I do not understand you, let's see what he says @KingFelix

**Comment by julianofischer** [comment]
Hi @WaKeMaTTa, thank you for your answer.
I meant: to insert author information at the end (or beginning) of each post.
Anyway, I implemented a simple feature in my [blog](http://www.julianofischernaves.me).
However, my limited knowledge about github does not allow me to create a pull request without messing up your source code. =(

**Comment by KingFelix** [comment]
Hello @julianofischer, I'm sorry but Emerald was thought as a personal blog, with a single author.
However your solution looks good!
I think I should add this feature into the future version of the project.
Thanks for your suggestion and the interest on the Emerald!
