### ISSUE TITLE
Lots of menu items and mobile screen size

### ISSUE THREAD

**Issue by ansonl** [KingFelix/emerald#7]
Hi,

When I add multiple menu items and there are 8 items, when you view the menu on a smaller screen size like the iPhone, you cannot scroll down to see the bottom items. Is there a fix for this? Thanks.

**Comment by KingFelix** [comment]
Hello! Sorry for the late reply...

I have taken note of the problem and I'll try to solve it in the next version!

**Comment by KingFelix** [comment]
Ok, I'm working on a new release of Emerald, but you can fix the problem adding `overflow:auto` to the `nav` tag of the menu.

p.s. I'm very sorry for the late response... :(
